import { Product } from '../types/product';
import { PledgedFund } from '../types/emi';
import { TopBrand, NearbyStore } from '../types/store';

export const MOCK_TOP_BRANDS: TopBrand[] = [
  {
    id: 'brand-apple',
    name: 'Apple',
    slug: 'apple',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    bannerColor: '#1d1d1f',
    category: 'smartphones',
    cashbackOffer: 'Flat ₹5,000 instant discount via 1Fi Mutual Funds',
    maxNoCostTenure: 12,
    featuredProductsCount: 18,
    websiteUrl: 'https://apple.com/in',
    popularItems: ['iPhone 16 Pro', 'MacBook Air M3', 'Apple Watch Series 10', 'AirPods Pro 2'],
  },
  {
    id: 'brand-samsung',
    name: 'Samsung',
    slug: 'samsung',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
    bannerColor: '#1428a0',
    category: 'electronics',
    cashbackOffer: 'Up to ₹8,000 voucher + 0% interest for 12 months',
    maxNoCostTenure: 12,
    featuredProductsCount: 24,
    websiteUrl: 'https://samsung.com/in',
    popularItems: ['Galaxy S24 Ultra', 'Galaxy Z Fold 6', 'Neo QLED 4K TV', 'Galaxy Book4'],
  },
  {
    id: 'brand-croma',
    name: 'Croma',
    slug: 'croma',
    logo: 'https://1fi.in/croma.webp',
    bannerColor: '#00838f',
    category: 'electronics',
    cashbackOffer: 'Extra 5% discount across all electronics & appliances',
    maxNoCostTenure: 12,
    featuredProductsCount: 65,
    websiteUrl: 'https://croma.com',
    popularItems: ['Laptops', 'Refrigerators', 'Smart TVs', 'Soundbars'],
  },
  {
    id: 'brand-reliance-digital',
    name: 'Reliance Digital',
    slug: 'reliance-digital',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Reliance_Digital_Logo.svg',
    bannerColor: '#e31e24',
    category: 'electronics',
    cashbackOffer: 'No-cost EMI + free express 3-hour store pickup',
    maxNoCostTenure: 12,
    featuredProductsCount: 50,
    websiteUrl: 'https://reliancedigital.in',
    popularItems: ['Gaming Laptops', 'Tablets', 'Washing Machines', 'Air Conditioners'],
  },
  {
    id: 'brand-oneplus',
    name: 'OnePlus',
    slug: 'oneplus',
    logo: 'https://1fi.in/oneplus15_home.webp',
    bannerColor: '#eb0028',
    category: 'smartphones',
    cashbackOffer: 'Free accidental damage protection with 1Fi pledge',
    maxNoCostTenure: 12,
    featuredProductsCount: 12,
    websiteUrl: 'https://oneplus.in',
    popularItems: ['OnePlus 12 5G', 'OnePlus Nord 4', 'OnePlus Watch 2', 'OnePlus Pad 2'],
  },
  {
    id: 'brand-sony',
    name: 'Sony Electronics',
    slug: 'sony',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg',
    bannerColor: '#000000',
    category: 'audio',
    cashbackOffer: 'Special audiophile 0% EMI financing up to 12 months',
    maxNoCostTenure: 12,
    featuredProductsCount: 15,
    websiteUrl: 'https://sony.co.in',
    popularItems: ['WH-1000XM5', 'PlayStation 5 Slim', 'Bravia XR OLED', 'Alpha 7 IV Camera'],
  },
  {
    id: 'brand-dyson',
    name: 'Dyson India',
    slug: 'dyson',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Dyson_logo.svg',
    bannerColor: '#ff2c79',
    category: 'appliances',
    cashbackOffer: 'Complimentary styling kit with Airwrap on 1Fi LAMF',
    maxNoCostTenure: 12,
    featuredProductsCount: 10,
    websiteUrl: 'https://dyson.in',
    popularItems: ['Airwrap Multi-Styler', 'V15 Detect Vacuum', 'Purifier Hot+Cool'],
  },
  {
    id: 'brand-boat',
    name: 'boAt Lifestyle',
    slug: 'boat',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Boat_logo.svg',
    bannerColor: '#e02020',
    category: 'audio',
    cashbackOffer: 'Instant 10% cash discount with 0 down payment',
    maxNoCostTenure: 6,
    featuredProductsCount: 30,
    websiteUrl: 'https://boat-lifestyle.com',
    popularItems: ['Airdopes Pro', 'Wave Smartwatch', 'Stone 1500 Speaker'],
  },
];

export const MOCK_NEARBY_STORES: NearbyStore[] = [
  {
    id: 'store-croma-cyberhub',
    name: 'Croma Cyber Hub',
    brand: 'Croma',
    logo: 'https://1fi.in/croma.webp',
    category: 'Multi-brand Electronics',
    address: 'DLF Cyber Hub, Ground Floor, Sector 24',
    city: 'Gurugram',
    pincode: '122002',
    distanceKm: 0.8,
    isOpen: true,
    timing: '10:30 AM - 10:00 PM',
    phone: '+91 124 456 7890',
    acceptedFinancing: 'Scan & Pay via 1Fi QR',
    rating: 4.6,
    reviewsCount: 840,
  },
  {
    id: 'store-imagine-galleria',
    name: 'Imagine Apple Authorised Premium Reseller',
    brand: 'Apple',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    category: 'Apple Official Partner',
    address: 'Shop 42, Galleria Market, DLF Phase 4',
    city: 'Gurugram',
    pincode: '122009',
    distanceKm: 1.4,
    isOpen: true,
    timing: '11:00 AM - 9:30 PM',
    phone: '+91 124 411 2233',
    acceptedFinancing: 'Direct 1Fi In-Store POS Financing',
    rating: 4.8,
    reviewsCount: 1250,
  },
  {
    id: 'store-reliance-ambience',
    name: 'Reliance Digital Ambience Mall',
    brand: 'Reliance Digital',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Reliance_Digital_Logo.svg',
    category: 'Consumer Electronics & IT',
    address: 'Ambience Mall, 2nd Floor, NH-8',
    city: 'Gurugram',
    pincode: '122002',
    distanceKm: 2.1,
    isOpen: true,
    timing: '10:00 AM - 10:00 PM',
    phone: '+91 124 499 8877',
    acceptedFinancing: 'Instant 1Fi QR Checkout',
    rating: 4.5,
    reviewsCount: 670,
  },
  {
    id: 'store-samsung-smartcafe',
    name: 'Samsung SmartCafe Sector 29',
    brand: 'Samsung',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
    category: 'Flagship Smartphones & Laptops',
    address: 'SCO 14, Main Market, Sector 29',
    city: 'Gurugram',
    pincode: '122001',
    distanceKm: 2.7,
    isOpen: true,
    timing: '10:30 AM - 9:00 PM',
    phone: '+91 124 400 1122',
    acceptedFinancing: '1Fi Mutual Fund EMI Desk',
    rating: 4.7,
    reviewsCount: 520,
  },
  {
    id: 'store-vijay-sales-mgroad',
    name: 'Vijay Sales MG Road',
    brand: 'Vijay Sales',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Vijay_Sales_logo.png',
    category: 'Home Appliances & Gadgets',
    address: 'MGF Metropolitan Mall, Ground Floor, MG Road',
    city: 'Gurugram',
    pincode: '122002',
    distanceKm: 3.2,
    isOpen: true,
    timing: '10:30 AM - 9:30 PM',
    phone: '+91 124 433 9900',
    acceptedFinancing: 'Scan & Pay via 1Fi QR',
    rating: 4.4,
    reviewsCount: 410,
  },
  {
    id: 'store-bose-cyberpark',
    name: 'Bose Premium Audio Lounge',
    brand: 'Bose',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Bose_logo.svg',
    category: 'High-End Audio Experience',
    address: 'One Horizon Center, Golf Course Road',
    city: 'Gurugram',
    pincode: '122003',
    distanceKm: 4.5,
    isOpen: true,
    timing: '11:00 AM - 8:30 PM',
    phone: '+91 124 488 5544',
    acceptedFinancing: '1Fi Premium Checkout',
    rating: 4.9,
    reviewsCount: 310,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-iphone-16-pro-max',
    slug: 'iphone-16-pro-max',
    name: 'Apple iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'smartphones',
    tagline: 'Titanium beauty. Ultimate A18 Pro performance.',
    description: 'iPhone 16 Pro Max features a grade 5 titanium design with a new, refined microblasted finish. Powered by the A18 Pro chip, it enables groundbreaking battery life, camera control, and advanced computational photography.',
    rating: 4.9,
    reviewsCount: 1420,
    defaultPrice: 144900,
    defaultOriginalPrice: 154900,
    lowestMonthlyEMI: 12075,
    deliveryDays: 1,
    isBestSeller: true,
    isNew: true,
    featuredDeal: true,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-16pm-256-desert',
        name: '256GB - Desert Titanium',
        storage: '256GB',
        ram: '8GB',
        colorName: 'Desert Titanium',
        colorHex: '#C5A898',
        price: 144900,
        originalPrice: 154900,
        inStock: true,
        imageIndex: 0,
      },
      {
        id: 'var-16pm-256-natural',
        name: '256GB - Natural Titanium',
        storage: '256GB',
        ram: '8GB',
        colorName: 'Natural Titanium',
        colorHex: '#9E9993',
        price: 144900,
        originalPrice: 154900,
        inStock: true,
        imageIndex: 0,
      },
      {
        id: 'var-16pm-512-black',
        name: '512GB - Black Titanium',
        storage: '512GB',
        ram: '8GB',
        colorName: 'Black Titanium',
        colorHex: '#2C2B29',
        price: 164900,
        originalPrice: 174900,
        inStock: true,
        imageIndex: 1,
      },
      {
        id: 'var-16pm-1tb-white',
        name: '1TB - White Titanium',
        storage: '1TB',
        ram: '8GB',
        colorName: 'White Titanium',
        colorHex: '#EAE6E1',
        price: 184900,
        originalPrice: 194900,
        inStock: true,
        imageIndex: 2,
      },
    ],
    specs: [
      {
        category: 'Display & Design',
        items: [
          { label: 'Screen Size', value: '6.9-inch Super Retina XDR' },
          { label: 'Refresh Rate', value: '120Hz ProMotion' },
          { label: 'Build', value: 'Grade 5 Titanium with Ceramic Shield' },
        ],
      },
      {
        category: 'Performance',
        items: [
          { label: 'Processor', value: 'A18 Pro with 6-core GPU' },
          { label: 'Neural Engine', value: '16-core Apple Intelligence' },
        ],
      },
      {
        category: 'Camera System',
        items: [
          { label: 'Main Sensor', value: '48MP Fusion Camera' },
          { label: 'Telephoto', value: '12MP 5x Optical Zoom' },
          { label: 'Video', value: '4K 120fps Dolby Vision' },
        ],
      },
      {
        category: 'Battery & Charging',
        items: [
          { label: 'Battery Life', value: 'Up to 33 hours video playback' },
          { label: 'Fast Charge', value: '50% in 30 minutes via MagSafe' },
        ],
      },
    ],
    highlights: [
      '0% Interest 12-Month EMI backed by your Mutual Funds',
      'No credit card or CIBIL check required',
      'Your mutual funds keep earning returns while you enjoy your phone',
      '1 Year Official Apple India Warranty included',
      'Same-day dispatch & verified genuine guarantee',
    ],
  },
  {
    id: 'prod-galaxy-s24-ultra',
    slug: 'galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra 5G',
    brand: 'Samsung',
    category: 'smartphones',
    tagline: 'Galaxy AI is here. Epic zoom and titanium frame.',
    description: 'Meet Galaxy S24 Ultra with a titanium exterior, flat 6.8-inch display, built-in S Pen, and Galaxy AI capabilities that redefine search, translation, and mobile productivity.',
    rating: 4.8,
    reviewsCount: 980,
    defaultPrice: 129999,
    defaultOriginalPrice: 139999,
    lowestMonthlyEMI: 10833,
    deliveryDays: 1,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-s24u-256-gray',
        name: '256GB - Titanium Gray',
        storage: '256GB',
        ram: '12GB',
        colorName: 'Titanium Gray',
        colorHex: '#5B5A5F',
        price: 129999,
        originalPrice: 139999,
        inStock: true,
        imageIndex: 0,
      },
      {
        id: 'var-s24u-512-black',
        name: '512GB - Titanium Black',
        storage: '512GB',
        ram: '12GB',
        colorName: 'Titanium Black',
        colorHex: '#2B2B2B',
        price: 139999,
        originalPrice: 149999,
        inStock: true,
        imageIndex: 1,
      },
      {
        id: 'var-s24u-1tb-violet',
        name: '1TB - Titanium Violet',
        storage: '1TB',
        ram: '12GB',
        colorName: 'Titanium Violet',
        colorHex: '#4E485B',
        price: 159999,
        originalPrice: 169999,
        inStock: true,
        imageIndex: 0,
      },
    ],
    specs: [
      {
        category: 'Display & S-Pen',
        items: [
          { label: 'Display', value: '6.8" Dynamic AMOLED 2X 120Hz' },
          { label: 'Brightness', value: '2600 nits Peak Brightness' },
          { label: 'Stylus', value: 'Integrated S Pen included' },
        ],
      },
      {
        category: 'Camera',
        items: [
          { label: 'Primary', value: '200MP Wide Angle' },
          { label: 'Telephoto', value: '50MP 5x Optical + 10MP 3x Optical' },
        ],
      },
      {
        category: 'Performance',
        items: [
          { label: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
          { label: 'AI Engine', value: 'Galaxy AI with Circle to Search' },
        ],
      },
    ],
    highlights: [
      'Instant approval using Mutual Fund lien pledge',
      '0% No-Cost EMI for up to 12 months',
      'Zero paperwork, zero foreclosure charges',
      '1 Year Samsung India Brand Warranty',
    ],
  },
  {
    id: 'prod-macbook-pro-m3',
    slug: 'macbook-pro-14-m3',
    name: 'Apple MacBook Pro 14" M3 Pro',
    brand: 'Apple',
    category: 'laptops',
    tagline: 'Mind-blowing performance with extreme battery life.',
    description: 'The 14-inch MacBook Pro with M3 Pro takes its power and efficiency further than ever. Delivering exceptional battery life and a stunning Liquid Retina XDR display.',
    rating: 4.9,
    reviewsCount: 712,
    defaultPrice: 199900,
    defaultOriginalPrice: 209900,
    lowestMonthlyEMI: 16658,
    deliveryDays: 2,
    isBestSeller: false,
    isNew: false,
    featuredDeal: true,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-mbp-18-512-black',
        name: '18GB RAM / 512GB SSD - Space Black',
        storage: '512GB SSD',
        ram: '18GB',
        colorName: 'Space Black',
        colorHex: '#1F2022',
        price: 199900,
        originalPrice: 209900,
        inStock: true,
      },
      {
        id: 'var-mbp-18-1tb-silver',
        name: '18GB RAM / 1TB SSD - Silver',
        storage: '1TB SSD',
        ram: '18GB',
        colorName: 'Silver',
        colorHex: '#E2E3E5',
        price: 239900,
        originalPrice: 249900,
        inStock: true,
      },
      {
        id: 'var-mbp-36-1tb-black',
        name: '36GB RAM / 1TB SSD - Space Black',
        storage: '1TB SSD',
        ram: '36GB',
        colorName: 'Space Black',
        colorHex: '#1F2022',
        price: 279900,
        originalPrice: 289900,
        inStock: true,
      },
    ],
    specs: [
      {
        category: 'Display',
        items: [
          { label: 'Screen', value: '14.2-inch Liquid Retina XDR' },
          { label: 'Peak Brightness', value: '1600 nits HDR' },
        ],
      },
      {
        category: 'Processor',
        items: [
          { label: 'CPU', value: '11-core CPU' },
          { label: 'GPU', value: '14-core GPU with Hardware Ray Tracing' },
        ],
      },
      {
        category: 'Battery',
        items: [
          { label: 'Runtime', value: 'Up to 18 hours' },
          { label: 'MagSafe', value: 'MagSafe 3 with 70W USB-C' },
        ],
      },
    ],
    highlights: [
      'Pledge your equity/debt mutual funds & keep earning gains',
      '0% interest over 12 months with ₹0 down payment',
      'Official Apple India invoice & warranty',
    ],
  },
  {
    id: 'prod-google-pixel-9-pro',
    slug: 'google-pixel-9-pro',
    name: 'Google Pixel 9 Pro XL',
    brand: 'Google',
    category: 'smartphones',
    tagline: 'Gemini-powered AI flagship with pro cameras.',
    description: 'Pixel 9 Pro XL delivers the best of Google AI first. Powered by Google Tensor G4 with 16GB of RAM for cutting-edge photography and advanced on-device Gemini capabilities.',
    rating: 4.7,
    reviewsCount: 540,
    defaultPrice: 124999,
    defaultOriginalPrice: 134999,
    lowestMonthlyEMI: 10416,
    deliveryDays: 1,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-px9-128-porcelain',
        name: '128GB - Porcelain',
        storage: '128GB',
        ram: '16GB',
        colorName: 'Porcelain',
        colorHex: '#F2EFEB',
        price: 124999,
        originalPrice: 134999,
        inStock: true,
      },
      {
        id: 'var-px9-256-hazel',
        name: '256GB - Hazel',
        storage: '256GB',
        ram: '16GB',
        colorName: 'Hazel',
        colorHex: '#7B8179',
        price: 134999,
        originalPrice: 144999,
        inStock: true,
      },
      {
        id: 'var-px9-512-obsidian',
        name: '512GB - Obsidian',
        storage: '512GB',
        ram: '16GB',
        colorName: 'Obsidian',
        colorHex: '#2D2D2E',
        price: 144999,
        originalPrice: 154999,
        inStock: true,
      },
    ],
    specs: [
      {
        category: 'Camera',
        items: [
          { label: 'Rear System', value: '50MP Main + 48MP Ultrawide + 48MP 5x Telephoto' },
          { label: 'Front Camera', value: '42MP Dual PD with autofocus' },
        ],
      },
      {
        category: 'Silicon & AI',
        items: [
          { label: 'Chipset', value: 'Google Tensor G4' },
          { label: 'AI Memory', value: '16GB RAM dedicated to Gemini Pro' },
        ],
      },
    ],
    highlights: [
      '7 Years of direct Android and security updates',
      'No-cost 0% EMI financed against your mutual funds',
      'Quick digital verification via PAN & phone',
    ],
  },
  {
    id: 'prod-sony-wh1000xm5',
    slug: 'sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    brand: 'Sony',
    category: 'audio',
    tagline: 'Industry-leading noise cancellation with auto NC optimizer.',
    description: 'With two processors and eight microphones, the WH-1000XM5 headphones deliver extraordinary noise cancellation and call quality in a lightweight, ergonomic design.',
    rating: 4.8,
    reviewsCount: 1890,
    defaultPrice: 29990,
    defaultOriginalPrice: 34990,
    lowestMonthlyEMI: 2499,
    deliveryDays: 1,
    featuredDeal: true,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-xm5-black',
        name: 'Standard - Black',
        colorName: 'Black',
        colorHex: '#181818',
        price: 29990,
        originalPrice: 34990,
        inStock: true,
      },
      {
        id: 'var-xm5-silver',
        name: 'Standard - Silver',
        colorName: 'Silver',
        colorHex: '#D8D4CC',
        price: 29990,
        originalPrice: 34990,
        inStock: true,
      },
      {
        id: 'var-xm5-navy',
        name: 'Standard - Midnight Blue',
        colorName: 'Midnight Blue',
        colorHex: '#1C2739',
        price: 31990,
        originalPrice: 36990,
        inStock: true,
      },
    ],
    specs: [
      {
        category: 'Audio',
        items: [
          { label: 'Driver Unit', value: '30mm specially designed' },
          { label: 'Codec Support', value: 'LDAC, AAC, SBC' },
          { label: 'Frequency Response', value: '4Hz - 40,000Hz' },
        ],
      },
      {
        category: 'Battery',
        items: [
          { label: 'Battery Life', value: 'Up to 30 hours with NC on' },
          { label: 'Quick Charge', value: '3 minutes charge = 3 hours playback' },
        ],
      },
    ],
    highlights: [
      '0% Interest 6-month or 12-month EMI',
      'Instant pledge approval with just ₹37,500 mutual fund units',
      '1 Year Sony India Official Warranty',
    ],
  },
  {
    id: 'prod-apple-watch-s10',
    slug: 'apple-watch-series-10',
    name: 'Apple Watch Series 10 (GPS + Cellular)',
    brand: 'Apple',
    category: 'wearables',
    tagline: 'Thinnest Apple Watch ever with our biggest display.',
    description: 'Series 10 is a major milestone for Apple Watch. It features the biggest, most advanced wide-angle OLED display, faster charging, and sleep apnea notifications.',
    rating: 4.8,
    reviewsCount: 630,
    defaultPrice: 49900,
    defaultOriginalPrice: 54900,
    lowestMonthlyEMI: 4158,
    deliveryDays: 1,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-w10-42-jetblack',
        name: '42mm - Jet Black Aluminium',
        colorName: 'Jet Black',
        colorHex: '#121212',
        price: 49900,
        originalPrice: 54900,
        inStock: true,
      },
      {
        id: 'var-w10-46-rosegold',
        name: '46mm - Rose Gold Aluminium',
        colorName: 'Rose Gold',
        colorHex: '#E8C5B8',
        price: 54900,
        originalPrice: 59900,
        inStock: true,
      },
      {
        id: 'var-w10-46-silver',
        name: '46mm - Silver Aluminium',
        colorName: 'Silver',
        colorHex: '#E3E3E3',
        price: 54900,
        originalPrice: 59900,
        inStock: true,
      },
    ],
    specs: [
      {
        category: 'Display',
        items: [
          { label: 'Screen', value: 'Wide-angle OLED Display' },
          { label: 'Thickness', value: '9.7mm thin' },
        ],
      },
      {
        category: 'Sensors',
        items: [
          { label: 'Health', value: 'ECG, Blood Oxygen, Temperature & Sleep Apnea' },
          { label: 'Depth', value: 'Water depth gauge & water temperature' },
        ],
      },
    ],
    highlights: [
      'Zero down payment required',
      'Pay in 6 or 12 installments from ₹4,158/month',
      'Mutual fund units remain secure and continue growing',
    ],
  },
  {
    id: 'prod-ipad-air-m2',
    slug: 'ipad-air-11-m2',
    name: 'Apple iPad Air 11" M2',
    brand: 'Apple',
    category: 'tablets',
    tagline: 'Fresh Air. Supercharged by the M2 chip.',
    description: 'iPad Air is powered by the astonishingly fast Apple M2 chip. It features a stunning Liquid Retina display, a new landscape camera, and support for Apple Pencil Pro.',
    rating: 4.9,
    reviewsCount: 420,
    defaultPrice: 59900,
    defaultOriginalPrice: 64900,
    lowestMonthlyEMI: 4991,
    deliveryDays: 2,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-ipad-128-spacegray',
        name: '128GB Wi-Fi - Space Gray',
        storage: '128GB',
        colorName: 'Space Gray',
        colorHex: '#4E5054',
        price: 59900,
        originalPrice: 64900,
        inStock: true,
      },
      {
        id: 'var-ipad-256-starlight',
        name: '256GB Wi-Fi - Starlight',
        storage: '256GB',
        colorName: 'Starlight',
        colorHex: '#EBE5D8',
        price: 69900,
        originalPrice: 74900,
        inStock: true,
      },
      {
        id: 'var-ipad-256-blue',
        name: '256GB Wi-Fi - Blue',
        storage: '256GB',
        colorName: 'Blue',
        colorHex: '#A3B4C8',
        price: 69900,
        originalPrice: 74900,
        inStock: true,
      },
    ],
    specs: [
      {
        category: 'Hardware',
        items: [
          { label: 'Chipset', value: 'Apple M2 Chip with 8-core CPU' },
          { label: 'Display', value: '11-inch Liquid Retina with True Tone' },
        ],
      },
      {
        category: 'Accessories',
        items: [
          { label: 'Pencil Support', value: 'Apple Pencil Pro & Apple Pencil USB-C' },
          { label: 'Keyboard', value: 'Magic Keyboard compatible' },
        ],
      },
    ],
    highlights: [
      'No-cost EMI over 12 months with 0% interest',
      'No CIBIL hit or personal loan documentation',
      '1 Year Apple Official Warranty',
    ],
  },
  {
    id: 'prod-oneplus-12',
    slug: 'oneplus-12-5g',
    name: 'OnePlus 12 5G',
    brand: 'OnePlus',
    category: 'smartphones',
    tagline: 'Smooth beyond belief. 4th Gen Hasselblad Camera.',
    description: 'Powered by Snapdragon 8 Gen 3 with up to 16GB of LPDDR5X RAM and 100W SUPERVOOC charging. Equipped with the 4th Gen Hasselblad Camera System for Mobile.',
    rating: 4.7,
    reviewsCount: 880,
    defaultPrice: 64999,
    defaultOriginalPrice: 69999,
    lowestMonthlyEMI: 5416,
    deliveryDays: 1,
    featuredDeal: true,
    images: [
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    ],
    variants: [
      {
        id: 'var-op12-256-black',
        name: '256GB - Silky Black',
        storage: '256GB',
        ram: '12GB',
        colorName: 'Silky Black',
        colorHex: '#1F1F1F',
        price: 64999,
        originalPrice: 69999,
        inStock: true,
      },
      {
        id: 'var-op12-512-emerald',
        name: '512GB - Flowy Emerald',
        storage: '512GB',
        ram: '16GB',
        colorName: 'Flowy Emerald',
        colorHex: '#1B4D3E',
        price: 69999,
        originalPrice: 74999,
        inStock: true,
      },
    ],
    specs: [
      {
        category: 'Charging & Battery',
        items: [
          { label: 'Battery', value: '5400 mAh high-capacity dual-cell' },
          { label: 'Charging', value: '100W SUPERVOOC (0-100% in 26 mins)' },
        ],
      },
      {
        category: 'Camera',
        items: [
          { label: 'Sensor', value: '50MP Sony LYT-808 with OIS' },
          { label: 'Telephoto', value: '64MP 3x Periscope Telephoto' },
        ],
      },
    ],
    highlights: [
      '1Fi Mutual Fund-backed checkout financing',
      '0% Interest for 12 months (₹5,416/mo)',
      '1 Year Official OnePlus Warranty',
    ],
  },
];

export const MOCK_USER_PORTFOLIO: PledgedFund[] = [
  {
    id: 'mf-1',
    schemeName: 'Parag Parikh Flexi Cap Fund - Direct (G)',
    category: 'Equity',
    units: 1782.45,
    nav: 81.45,
    currentValue: 145180,
    pledgedValue: 0,
    amcLogo: 'PPFAS',
  },
  {
    id: 'mf-2',
    schemeName: 'Mirae Asset Large & Midcap Fund - Direct (G)',
    category: 'Equity',
    units: 820.12,
    nav: 120.35,
    currentValue: 98700,
    pledgedValue: 0,
    amcLogo: 'Mirae',
  },
  {
    id: 'mf-3',
    schemeName: 'HDFC Mid-Cap Opportunities Fund - Direct (G)',
    category: 'Equity',
    units: 750.0,
    nav: 160.75,
    currentValue: 120560,
    pledgedValue: 0,
    amcLogo: 'HDFC',
  },
  {
    id: 'mf-4',
    schemeName: 'ICICI Prudential Technology Fund - Direct (G)',
    category: 'Equity',
    units: 412.3,
    nav: 186.25,
    currentValue: 76790,
    pledgedValue: 0,
    amcLogo: 'ICICI',
  },
];
